services:
  xylozen-app:
    image: ghcr.io/byte-bandits-india/xylozen:latest
    container_name: xylozen-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:3000:3000"
    deploy:
      resources:
        limits:
          memory: 512M
