services:
  xylozen-app:
    image: ghcr.io/byte-bandits-india/xylozen:latest
    container_name: xylozen-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - app
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  app:
    name: dashboard_app
    external: true
